# Generated by Django 3.0.4 on 2020-12-11 15:17

import classes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0019_auto_20200408_1622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0013_days_semester'),
        ('tutorials', '0030_auto_20200408_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClass',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', martor.models.MartorField(blank=True, max_length=2000)),
                ('time', models.TimeField()),
                ('number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('ug', models.BooleanField(default=False)),
                ('grad', models.BooleanField(default=False)),
                ('prereqs', models.CharField(max_length=100)),
                ('canvas', models.URLField()),
                ('dept_site', models.URLField()),
                ('banner', models.TextField(blank=True, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.Institution')),
                ('semester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cal.Semester')),
            ],
            options={
                'verbose_name': 'historical class',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', martor.models.MartorField(blank=True, max_length=2000)),
                ('time', models.TimeField()),
                ('number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('ug', models.BooleanField(default=False)),
                ('grad', models.BooleanField(default=False)),
                ('prereqs', models.CharField(max_length=100)),
                ('canvas', models.URLField()),
                ('dept_site', models.URLField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to=classes.models.banner_filename)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('days', models.ManyToManyField(to='cal.Days')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Institution')),
                ('instructors', models.ManyToManyField(to='people.Person')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.Semester')),
                ('skills', models.ManyToManyField(blank=True, to='tutorials.Skill')),
                ('software', models.ManyToManyField(blank=True, to='tutorials.Software')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
    ]
