# Generated by Django 3.0.4 on 2020-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='units',
            field=models.SmallIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclass',
            name='units',
            field=models.SmallIntegerField(default=6),
            preserve_default=False,
        ),
    ]
