# Generated by Django 3.0.4 on 2020-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201211_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='lab1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lab2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lecture1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lecture2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lecture3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclass',
            name='lab1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclass',
            name='lab2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclass',
            name='lecture1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclass',
            name='lecture2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclass',
            name='lecture3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='prereqs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='units',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='prereqs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='units',
            field=models.CharField(max_length=15),
        ),
    ]
