# Generated by Django 3.0.4 on 2020-12-11 23:44

import classes.models
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0030_auto_20200408_1257'),
        ('cal', '0016_auto_20201211_1028'),
        ('people', '0019_auto_20200408_1622'),
        ('classes', '0004_auto_20201211_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='class',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='class',
            name='dept_site',
        ),
        migrations.RemoveField(
            model_name='class',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='class',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='class',
            name='location',
        ),
        migrations.RemoveField(
            model_name='class',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='class',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='class',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='class',
            name='software',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='dept_site',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalclass',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='historicalsessiontype',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='cl',
        ),
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', martor.models.MartorField(blank=True, max_length=2000)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('canvas', models.URLField()),
                ('dept_site', models.URLField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to=classes.models.banner_filename)),
                ('class_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('instructors', models.ManyToManyField(to='people.Person')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.Semester')),
                ('sessions', models.ManyToManyField(blank=True, through='classes.SessionType', to='classes.SessionTime')),
                ('skills', models.ManyToManyField(blank=True, to='tutorials.Skill')),
                ('software', models.ManyToManyField(blank=True, to='tutorials.Software')),
            ],
        ),
        migrations.AddField(
            model_name='historicalsessiontype',
            name='class_instance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classes.ClassInstance'),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.ClassInstance'),
        ),
    ]
