# Generated by Django 3.0.4 on 2020-12-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20201211_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classinstance',
            options={'verbose_name': 'class instance', 'verbose_name_plural': 'class instances'},
        ),
        migrations.RemoveField(
            model_name='classinstance',
            name='class_model',
        ),
        migrations.AddField(
            model_name='classinstance',
            name='cl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='classes.ClassInstance'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='session_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='classes.SessionTime'),
        ),
    ]
