# Generated by Django 3.0.4 on 2020-12-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_auto_20201211_1028'),
        ('classes', '0006_auto_20201216_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontime',
            name='days',
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='days',
            field=models.ManyToManyField(to='cal.Days'),
        ),
    ]
