# Generated by Django 3.0.4 on 2020-12-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20201216_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_type', to='classes.ClassInstance'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='session_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_type', to='classes.SessionTime'),
        ),
    ]
