# Generated by Django 3.0.4 on 2020-12-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20201216_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinstance',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
