# Generated by Django 3.0.4 on 2020-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_classinstance_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
