# Generated by Django 3.0.4 on 2020-12-17 23:43

import datetime

from django.db import migrations

def create_through_relations(apps, schema_editor):
    ClassInstance = apps.get_model('classes', 'ClassInstance')
    InstructorOrder = apps.get_model('classes', 'InstructorOrder')
    for inst in ClassInstance.objects.all():
        for instructor in inst.instructors.all():
            InstructorOrder(
                class_instance = inst,
                instructor = instructor,
                order = 0
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_historicalinstructororder_instructororder'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
