# Generated by Django 3.0.4 on 2020-12-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20201217_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstructororder',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructororder',
            name='instructor',
        ),
    ]
