# Generated by Django 3.0.4 on 2020-12-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20201217_1420'),
        ('classes', '0014_auto_20201217_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstructororder',
            name='instructor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.Person'),
        ),
        migrations.AddField(
            model_name='instructororder',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_order', to='people.Person'),
        ),
    ]
