# Generated by Django 3.0.4 on 2020-12-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_auto_20201217_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinstance',
            name='instructors',
        ),
    ]
