# Generated by Django 3.0.4 on 2021-02-22 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_classinstance_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstructororder',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='historicalinstructororder',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinstructororder',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='historicalsessiontype',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='historicalsessiontype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsessiontype',
            name='session_time',
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='HistoricalClass',
        ),
        migrations.DeleteModel(
            name='HistoricalInstructorOrder',
        ),
        migrations.DeleteModel(
            name='HistoricalSessionType',
        ),
    ]
