# Generated by Django 3.0.4 on 2021-02-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_auto_20210222_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='class',
            name='published',
        ),
    ]
