# Generated by Django 3.0.4 on 2020-03-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1500)),
                ('virtual_url', models.URLField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ticket_url', models.URLField(null=True)),
                ('cancel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=150, null=True)),
                ('inst', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=25)),
                ('middle', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=250)),
                ('website', models.URLField(max_length=250)),
                ('pronouns', models.CharField(choices=[('M', 'He/him/his'), ('W', 'She/her/hers'), ('T', 'They/them/theirs')], default='T', max_length=1)),
                ('orcid', models.CharField(max_length=19, null=True)),
                ('pgp', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('gitlab', models.CharField(max_length=25, null=True)),
                ('github', models.CharField(max_length=25, null=True)),
                ('affil', models.ManyToManyField(through='cal.Affiliation', to='cal.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('definition', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('D', 'Discussant'), ('M', 'Moderator'), ('P', 'Panelist'), ('L', 'Lecturer'), ('I', 'Introducer'), ('W', 'Workshop Leader')], default='L', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(through='cal.Role', to='cal.Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(to='cal.Topic'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Venue'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Institution'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Participant'),
        ),
    ]
