# Generated by Django 3.0.4 on 2020-03-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='virtual_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='github',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gitlab',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='middle',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='participant',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pgp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
