# Generated by Django 3.0.4 on 2020-03-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('cal', '0002_auto_20200320_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='affil',
        ),
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(through='cal.Role', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='role',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Institution'),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
