# Generated by Django 3.0.4 on 2020-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200401_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
