# Generated by Django 3.0.4 on 2020-04-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20200401_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventmetadata',
            options={'verbose_name': 'event app metadata', 'verbose_name_plural': 'event app metadata'},
        ),
        migrations.AlterModelOptions(
            name='historicaleventmetadata',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical event app metadata'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'venue', 'verbose_name_plural': 'venues'},
        ),
    ]
