# Generated by Django 3.0.4 on 2020-04-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0029_auto_20200406_1757'),
        ('cal', '0007_auto_20200401_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorials.Module'),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='module',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tutorials.Module'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.Venue'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
