# Generated by Django 3.0.4 on 2020-04-07 11:59

import cal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_auto_20200407_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=cal.models.banner_filename),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='banner',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
