# Generated by Django 3.0.4 on 2020-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_auto_20200408_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('S', 'Spring'), ('F', 'Fall'), ('I', 'IAP'), ('M', 'Summer')], default='T', max_length=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
