# Generated by Django 3.0.4 on 2020-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_days_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='abbrev',
            field=models.CharField(default='tu', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='days',
            name='order',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
