# Generated by Django 3.0.4 on 2021-02-22 17:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_auto_20201211_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaleventmetadata',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='historicaltopic',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvenue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvenue',
            name='inst',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=150, null=True, populate_from='title'),
        ),
        migrations.DeleteModel(
            name='HistoricalEvent',
        ),
        migrations.DeleteModel(
            name='HistoricalEventMetadata',
        ),
        migrations.DeleteModel(
            name='HistoricalRole',
        ),
        migrations.DeleteModel(
            name='HistoricalTopic',
        ),
        migrations.DeleteModel(
            name='HistoricalVenue',
        ),
    ]
