# Generated by Django 3.0.4 on 2020-03-31 16:04

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_desc', models.CharField(max_length=80)),
                ('about', markdownx.models.MarkdownxField(max_length=2000)),
                ('twitter', models.CharField(blank=True, default='', max_length=50)),
                ('instagram', models.CharField(blank=True, default='', max_length=50)),
                ('gitlab', models.CharField(blank=True, default='', max_length=25)),
                ('github', models.CharField(blank=True, default='', max_length=25)),
                ('zotero', models.CharField(blank=True, default='', max_length=25)),
                ('linkedin', models.CharField(blank=True, default='', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
