# Generated by Django 3.0.4 on 2020-04-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200401_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmetadata',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mainmetadata',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.CreateModel(
            name='HistoricalMainMetadata',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('main_name', models.CharField(max_length=20)),
                ('short_desc', models.CharField(max_length=80)),
                ('about_name', models.CharField(max_length=20)),
                ('about', markdownx.models.MarkdownxField(max_length=2000)),
                ('twitter', models.CharField(blank=True, default='', max_length=50)),
                ('gitlab', models.CharField(blank=True, default='', max_length=25)),
                ('github', models.CharField(blank=True, default='', max_length=25)),
                ('zotero', models.CharField(blank=True, default='', max_length=25)),
                ('linkedin', models.CharField(blank=True, default='', max_length=25)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical main metadata',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
