# Generated by Django 3.0.4 on 2020-04-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200401_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmainmetadata',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical main app metadata'},
        ),
        migrations.AlterModelOptions(
            name='mainmetadata',
            options={'verbose_name': 'main app metadata', 'verbose_name_plural': 'main app metadata'},
        ),
    ]
