# Generated by Django 3.0.4 on 2020-04-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200401_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmainmetadata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mainmetadata',
            name='created_at',
        ),
    ]
