# Generated by Django 3.0.4 on 2020-04-01 19:14

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200401_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmainmetadata',
            name='about',
            field=martor.models.MartorField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mainmetadata',
            name='about',
            field=martor.models.MartorField(max_length=2000),
        ),
    ]
