# Generated by Django 3.0.4 on 2020-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201216_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmainmetadata',
            name='short_desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='mainmetadata',
            name='short_desc',
            field=models.CharField(max_length=400),
        ),
    ]
