# Generated by Django 3.0.4 on 2020-12-17 00:13

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201216_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmainmetadata',
            name='colophon',
            field=martor.models.MartorField(blank=True, default='', max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='historicalmainmetadata',
            name='colophone_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='mainmetadata',
            name='colophon',
            field=martor.models.MartorField(blank=True, default='', max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='mainmetadata',
            name='colophone_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
