# Generated by Django 3.0.4 on 2020-12-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201216_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmainmetadata',
            name='colophone_name',
        ),
        migrations.RemoveField(
            model_name='mainmetadata',
            name='colophone_name',
        ),
        migrations.AddField(
            model_name='historicalmainmetadata',
            name='colophon_name',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mainmetadata',
            name='colophon_name',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
