# Generated by Django 3.0.4 on 2020-12-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201216_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmainmetadata',
            name='colophon_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainmetadata',
            name='colophon_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
