# Generated by Django 3.0.4 on 2021-03-08 21:02

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201216_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmainmetadata',
            name='address',
            field=martor.models.MartorField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmainmetadata',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mainmetadata',
            name='address',
            field=martor.models.MartorField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmetadata',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
