# Generated by Django 3.0.4 on 2021-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210312_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmainmetadata',
            name='accessibility_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mainmetadata',
            name='accessibility_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
