# Generated by Django 3.0.4 on 2021-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210331_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmainmetadata',
            name='accessibility_url',
            field=models.URLField(blank=True, default='https://web.mit.edu/accessibility/'),
        ),
        migrations.AlterField(
            model_name='mainmetadata',
            name='accessibility_url',
            field=models.URLField(blank=True, default='https://web.mit.edu/accessibility/'),
        ),
    ]
