# Generated by Django 3.0.4 on 2020-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lib_type', models.CharField(choices=[('user', 'User library.'), ('group', 'Group library.')], default='group', max_length=5)),
                ('collection_key', models.CharField(choices=[('user', 'User library.'), ('group', 'Group library.')], default='group', max_length=5)),
            ],
        ),
    ]
