# Generated by Django 3.0.4 on 2020-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20200322_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='cite_style',
            field=models.CharField(choices=[('mla', 'Modern Language Association (MLA)'), ('chicago-author-date', 'Chicago (Author Date)'), ('taylor-and-francis-harvard-x', 'Harvard')], default='cad', max_length=30),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='lib_type',
            field=models.CharField(choices=[('user', 'User Library'), ('group', 'Group Library')], default='group', max_length=5),
        ),
    ]
