# Generated by Django 3.0.4 on 2020-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_auto_20200322_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='cite_style',
            field=models.CharField(choices=[('mla', 'Modern Language Association (MLA)'), ('chicago-author-date', 'Chicago (Author Date)'), ('taylor-and-francis-harvard-x', 'Harvard')], default='chicago-author-date', max_length=30),
        ),
    ]
