# Generated by Django 3.0.4 on 2020-03-26 21:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_readinglist_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingListMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', markdownx.models.MarkdownxField(blank=True, max_length=2000)),
            ],
        ),
    ]
