# Generated by Django 3.0.4 on 2020-03-31 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_readinglistmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinglist',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='readinglistmetadata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinglistmetadata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
