# Generated by Django 3.0.4 on 2020-04-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_auto_20200331_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingListMetadata',
            new_name='ReadingMetadata',
        ),
    ]
