# Generated by Django 3.0.4 on 2020-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_auto_20200401_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreadinglist',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalreadingmetadata',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
