# Generated by Django 3.0.4 on 2020-04-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_auto_20200401_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreadingmetadata',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reading list app metadata'},
        ),
        migrations.AlterModelOptions(
            name='readinglist',
            options={'verbose_name': 'reading list', 'verbose_name_plural': 'reading lists'},
        ),
        migrations.AlterModelOptions(
            name='readingmetadata',
            options={'verbose_name': 'reading list app metadata', 'verbose_name_plural': 'reading list app metadata'},
        ),
    ]
