# Generated by Django 3.0.4 on 2020-04-01 19:14

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_auto_20200401_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreadinglist',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalreadingmetadata',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='readingmetadata',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=2000),
        ),
    ]
