# Generated by Django 3.0.4 on 2020-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0012_auto_20200401_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreadinglist',
            name='collection_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='collection_key',
            field=models.CharField(max_length=20),
        ),
    ]
