# Generated by Django 3.0.4 on 2020-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0013_auto_20200406_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreadinglist',
            name='collection_key',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='collection_key',
            field=models.IntegerField(),
        ),
    ]
