# Generated by Django 3.0.4 on 2020-04-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0014_auto_20200406_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreadinglist',
            old_name='collection_key',
            new_name='library_id',
        ),
        migrations.RenameField(
            model_name='readinglist',
            old_name='collection_key',
            new_name='library_id',
        ),
    ]
