# Generated by Django 3.0.4 on 2020-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0015_auto_20200406_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreadinglist',
            name='collection_key',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinglist',
            name='collection_key',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
