# Generated by Django 3.0.4 on 2020-04-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0016_auto_20200406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreadinglist',
            name='collection_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='collection_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
