# Generated by Django 3.0.4 on 2021-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0017_auto_20200406_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreadingmetadata',
            name='history_user',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.DeleteModel(
            name='HistoricalReadingList',
        ),
        migrations.DeleteModel(
            name='HistoricalReadingMetadata',
        ),
    ]
