# Generated by Django 3.0.4 on 2021-05-12 13:47

from django.db import migrations, models
import reading.models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0018_auto_20210511_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=reading.models.banner_filename),
        ),
    ]
