# Generated by Django 3.0.4 on 2021-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0019_readinglist_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
