# Generated by Django 3.0.4 on 2020-03-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=150, null=True)),
                ('inst', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/images/photos')),
                ('first', models.CharField(max_length=25)),
                ('middle', models.CharField(blank=True, default='', max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('pronouns', models.CharField(choices=[('M', 'He/him/his'), ('W', 'She/her/hers'), ('T', 'They/them/theirs')], default='T', max_length=1)),
                ('orcid', models.CharField(blank=True, default='', max_length=19)),
                ('pgp', models.CharField(blank=True, default='', max_length=50)),
                ('twitter', models.CharField(blank=True, default='', max_length=50)),
                ('gitlab', models.CharField(blank=True, default='', max_length=25)),
                ('github', models.CharField(blank=True, default='', max_length=25)),
                ('affil', models.ManyToManyField(through='people.Affiliation', to='people.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Institution'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
