# Generated by Django 3.0.4 on 2020-03-26 16:08

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='desc',
            field=markdownx.models.MarkdownxField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/personphotos'),
        ),
    ]
