# Generated by Django 3.0.4 on 2020-03-26 16:45

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200326_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='bio',
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=people.models.photo_filename),
        ),
    ]
