# Generated by Django 3.0.4 on 2020-03-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200326_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
