# Generated by Django 3.0.4 on 2020-04-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20200401_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpeoplemetadata',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical people app metadata'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
        migrations.AlterModelOptions(
            name='peoplemetadata',
            options={'verbose_name': 'people app metadata', 'verbose_name_plural': 'people app metadata'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
