# Generated by Django 3.0.4 on 2020-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20200401_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstitution',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
