# Generated by Django 3.0.4 on 2020-04-01 19:14

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20200401_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpeoplemetadata',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='bio',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='peoplemetadata',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
    ]
