# Generated by Django 3.0.4 on 2020-04-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20200401_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalaffiliation',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
