# Generated by Django 3.0.4 on 2020-04-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20200406_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='title',
            field=models.CharField(choices=[('D', 'Director'), ('A', 'Affiliate'), ('R', 'Research Assistant'), ('F', 'Faculty Steering Committee'), ('L', 'Alumni Board')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('D', 'Director'), ('A', 'Affiliate'), ('R', 'Research Assistant'), ('F', 'Faculty Steering Committee'), ('L', 'Alumni Board')], default='', max_length=1),
        ),
    ]
