# Generated by Django 3.0.4 on 2020-12-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_auto_20200408_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='state',
        ),
        migrations.DeleteModel(
            name='HistoricalInstitution',
        ),
    ]
