# Generated by Django 3.0.4 on 2020-12-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20201216_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='abbr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='short',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
