# Generated by Django 3.0.4 on 2020-12-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20201216_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='dept_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='inst_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
