# Generated by Django 3.0.4 on 2020-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20201216_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='cred',
            field=models.CharField(blank=True, choices=[('MCP', 'Master of City Planning'), ('PhD', 'Doctor of Philosophy'), ('MUP', 'Master of Urban Planning'), ('MURP', 'Master of Urban and Regional Planning'), ('MFA', 'Master of Fine Arts'), ('MLA', 'Master of Landscape Architecture'), ('MArch', 'Master of Architecture'), ('MBA', 'Master of Business Administration'), ('MPA', 'Master of Public Administration'), ('MDes', 'Master of Design Studies'), ('DDes', 'Doctor of Design')], default='PhD', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cred',
            field=models.CharField(blank=True, choices=[('MCP', 'Master of City Planning'), ('PhD', 'Doctor of Philosophy'), ('MUP', 'Master of Urban Planning'), ('MURP', 'Master of Urban and Regional Planning'), ('MFA', 'Master of Fine Arts'), ('MLA', 'Master of Landscape Architecture'), ('MArch', 'Master of Architecture'), ('MBA', 'Master of Business Administration'), ('MPA', 'Master of Public Administration'), ('MDes', 'Master of Design Studies'), ('DDes', 'Doctor of Design')], default='PhD', max_length=5, null=True),
        ),
    ]
