# Generated by Django 3.0.4 on 2020-12-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20201217_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperson',
            name='terminal_degree',
        ),
        migrations.RemoveField(
            model_name='person',
            name='terminal_degree',
        ),
    ]
