# Generated by Django 3.0.4 on 2020-12-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_auto_20201217_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='people.Institution'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='people.Person'),
        ),
    ]
