# Generated by Django 3.0.4 on 2021-02-23 04:26

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20210222_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='vita',
            field=models.FileField(blank=True, default='', upload_to='people/vitae/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=martor.models.MartorField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
