# Generated by Django 3.0.4 on 2020-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/images/photos')),
                ('first', models.CharField(max_length=25)),
                ('middle', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('pronouns', models.CharField(choices=[('M', 'He/him/his'), ('W', 'She/her/hers'), ('T', 'They/them/theirs')], default='T', max_length=1)),
                ('orcid', models.CharField(max_length=19, null=True)),
                ('pgp', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('gitlab', models.CharField(max_length=25, null=True)),
                ('github', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='series/images/banners'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/images/banners'),
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.ManyToManyField(to='tutorials.Person'),
        ),
    ]
