# Generated by Django 3.0.4 on 2020-03-22 17:26

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('tutorials', '0002_auto_20200320_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='author',
            field=models.ManyToManyField(to='people.Person'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
