# Generated by Django 3.0.4 on 2020-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200322_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tutorials/images/banners')),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='skills',
            field=models.ManyToManyField(null=True, to='tutorials.Skill'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='software',
            field=models.ManyToManyField(null=True, to='tutorials.Software'),
        ),
    ]
