# Generated by Django 3.0.4 on 2020-03-26 15:27

from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20200326_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=tutorials.models.banner_filename),
        ),
        migrations.AlterField(
            model_name='software',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/images/icons'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=tutorials.models.banner_filename),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='skills',
            field=models.ManyToManyField(to='tutorials.Skill'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='software',
            field=models.ManyToManyField(to='tutorials.Software'),
        ),
    ]
