# Generated by Django 3.0.4 on 2020-03-26 15:50

from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20200326_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=tutorials.models.icon_filename),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='skills',
            field=models.ManyToManyField(blank=True, to='tutorials.Skill'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='software',
            field=models.ManyToManyField(blank=True, to='tutorials.Software'),
        ),
    ]
