# Generated by Django 3.0.4 on 2020-03-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_auto_20200326_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='series',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Series')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Tutorial')),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='series',
            field=models.ManyToManyField(blank=True, through='tutorials.Episode', to='tutorials.Series'),
        ),
    ]
