# Generated by Django 3.0.4 on 2020-03-26 18:17

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_auto_20200326_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='desc',
            field=markdownx.models.MarkdownxField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
