# Generated by Django 3.0.4 on 2020-03-26 21:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_software_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', markdownx.models.MarkdownxField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', markdownx.models.MarkdownxField(blank=True, max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='series',
            name='desc',
            field=markdownx.models.MarkdownxField(blank=True, max_length=2000),
        ),
    ]
