# Generated by Django 3.0.4 on 2020-03-26 21:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('people', '0004_auto_20200326_1645'),
        ('tutorials', '0010_auto_20200326_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Module',
        ),
        migrations.RenameModel(
            old_name='TutorialMetadata',
            new_name='ModuleMetadata',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='tutorial',
            new_name='module',
        ),
    ]
