# Generated by Django 3.0.4 on 2020-03-31 22:38

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_auto_20200331_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
