# Generated by Django 3.0.4 on 2020-04-01 13:44

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_auto_20200331_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialsMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=25)),
                ('app_desc', markdownx.models.MarkdownxField(blank=True, max_length=1000)),
                ('modules_name', models.CharField(max_length=25)),
                ('modules_desc', markdownx.models.MarkdownxField(blank=True, max_length=1000)),
                ('series_name', models.CharField(max_length=25)),
                ('series_desc', markdownx.models.MarkdownxField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModuleMetadata',
        ),
        migrations.DeleteModel(
            name='SeriesMetadata',
        ),
    ]
