# Generated by Django 3.0.4 on 2020-04-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_auto_20200401_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'episode', 'verbose_name_plural': 'episodes'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'software', 'verbose_name_plural': 'software'},
        ),
        migrations.AlterModelOptions(
            name='tutorialsmetadata',
            options={'verbose_name': 'tutorials metadata', 'verbose_name_plural': 'tutorials metadata'},
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='tutorialsmetadata',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tutorialsmetadata',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
