# Generated by Django 3.0.4 on 2020-04-01 15:12

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_historicalepisode_historicalmodule_historicalseries_historicalskill_historicalsoftware_historicaltut'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalskill',
            name='desc',
            field=markdownx.models.MarkdownxField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='desc',
            field=markdownx.models.MarkdownxField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
