# Generated by Django 3.0.4 on 2020-04-01 19:14

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_auto_20200401_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodule',
            name='body',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='historicalmodule',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalseries',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='historicalskill',
            name='desc',
            field=martor.models.MartorField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalsoftware',
            name='desc',
            field=martor.models.MartorField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltutorialsmetadata',
            name='app_desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicaltutorialsmetadata',
            name='modules_desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicaltutorialsmetadata',
            name='series_desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='module',
            name='body',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='series',
            name='desc',
            field=martor.models.MartorField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='desc',
            field=martor.models.MartorField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='desc',
            field=martor.models.MartorField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorialsmetadata',
            name='app_desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tutorialsmetadata',
            name='modules_desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tutorialsmetadata',
            name='series_desc',
            field=martor.models.MartorField(blank=True, max_length=1000),
        ),
    ]
