# Generated by Django 3.0.4 on 2020-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0021_auto_20200401_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='materials',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='materials',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
