# Generated by Django 3.0.4 on 2020-04-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0022_auto_20200401_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='historicalepisode',
            old_name='episode',
            new_name='number',
        ),
    ]
