# Generated by Django 3.0.4 on 2020-04-06 21:43

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0012_auto_20200401_1514'),
        ('tutorials', '0024_auto_20200401_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='readings',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reading.ReadingList'),
        ),
        migrations.AddField(
            model_name='historicalmodule',
            name='review',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmodule',
            name='start',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmodule',
            name='whatnext',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='readings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.ReadingList'),
        ),
        migrations.AddField(
            model_name='module',
            name='review',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='start',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='whatnext',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
    ]
