# Generated by Django 3.0.4 on 2020-04-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0012_auto_20200401_1514'),
        ('tutorials', '0026_auto_20200406_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodule',
            name='materials',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='materials',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='module',
            name='readings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.ReadingList'),
        ),
    ]
