# Generated by Django 3.0.4 on 2020-04-06 21:50

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0027_auto_20200406_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodule',
            name='body',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
