# Generated by Django 3.0.4 on 2020-04-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0029_auto_20200406_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalseries',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalseries',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
