# Generated by Django 3.0.4 on 2021-02-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0031_auto_20210211_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmodule',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmodule',
            name='readings',
        ),
        migrations.RemoveField(
            model_name='historicalseries',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalskill',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsoftware',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltutorialsmetadata',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='module',
            name='review',
        ),
        migrations.RemoveField(
            model_name='module',
            name='start',
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.DeleteModel(
            name='HistoricalEpisode',
        ),
        migrations.DeleteModel(
            name='HistoricalModule',
        ),
        migrations.DeleteModel(
            name='HistoricalSeries',
        ),
        migrations.DeleteModel(
            name='HistoricalSkill',
        ),
        migrations.DeleteModel(
            name='HistoricalSoftware',
        ),
        migrations.DeleteModel(
            name='HistoricalTutorialsMetadata',
        ),
    ]
